openapi: 3.0.3
info:
  title: Api
  description: API generated
  termsOfService: http:swagger.io/terms
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080/

tags:
  - name: User
    description: Operations to manage User
  - name: UserData
    description: Operations to manage UserData
  - name: Address
    description: Operations to manage Address  
  - name: Country
    description: Operations to manage Country  

paths:
  /user:
    $ref: user.yml#/~1user
  /user/{id}:
    $ref: user.yml#/~1user~1{id}
  /users:
    $ref: user.yml#/~1users
  /user/data:
    $ref: user.yml#/~1user~1data
  /user/data/{id}:
    $ref: user.yml#/~1user~1data~1{id}
    
  /address:
    $ref: address.yml#/~1address
  /address/{id}:
    $ref: address.yml#/~1address~1{id} 
  /addresses:
    $ref: address.yml#/~1addresses
    
  /address/country:
    $ref: address.yml#/~1address~1country  
  /address/country/{id}:
    $ref: address.yml#/~1address~1country~1{id} 