openapi: 3.0.3
info:
  title: Api
  description: API generated
  termsOfService: http:swagger.io/terms
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080/

tags:
  - name: User
    description: Operations to manage User
  - name: UserData
    description: Operations to manage UserData
  - name: UserActivated
    description: Operations to manage UserActivated
  - name: Profile
    description: Operations to manage Profile
  - name: Movement
    description: Operations to manage Movement
  - name: FixedMovement
    description: Operations to manage FixedMovement
  - name: SpendingExpectation
    description: Operations to manage SpendingExpectation

paths:

  /user:
    $ref: user.yml#/~1user
  /user/{id}:
    $ref: user.yml#/~1user~1{id}
  /user/login:
    $ref: user.yml#/~1user~1login
  /users:
    $ref: user.yml#/~1users
  /user/data/{id}:
    $ref: user.yml#/~1user~1data~1{id}
  /user/activated/{id}:
    $ref: user.yml#/~1user~1activated~1{id}
  /user/{id}/profiles:
    $ref: user.yml#/~1user~1{id}~1profiles
    
  /email:
    $ref: email.yml#/~1email
  /email/{id}:
    $ref: email.yml#/~1email~1{id}
  /emails:
    $ref: email.yml#/~1emails
    
  /phone:
    $ref: phone.yml#/~1phone
  /phone/{id}:
    $ref: phone.yml#/~1phone~1{id}
  /phones:
    $ref: phone.yml#/~1phones
    
  /profile:
    $ref: profile.yml#/~1profile
  /profile/{id}:
    $ref: profile.yml#/~1profile~1{id}
  /profiles:
    $ref: profile.yml#/~1profiles
  /profile/{id}/movements:
    $ref: profile.yml#/~1profile~1{id}~1movements
  /profile/{id}/fixed-movements:
    $ref: profile.yml#/~1profile~1{id}~1fixed-movements
  /profile/{id}/spending-expectations:
    $ref: profile.yml#/~1profile~1{id}~1spending-expectations
    
  /movement:
    $ref: movement.yml#/~1movement
  /movement/{id}:
    $ref: movement.yml#/~1movement~1{id}
  /movements:
    $ref: movement.yml#/~1movements
    
  /fixed-movement:
    $ref: fixed-movement.yml#/~1fixed-movement
  /fixed-movement/{id}:
    $ref: fixed-movement.yml#/~1fixed-movement~1{id}
  /fixed-movements:
    $ref: fixed-movement.yml#/~1fixed-movements
    
  /spending-expectation:
    $ref: spending-expectation.yml#/~1spending-expectation
  /spending-expectation/{id}:
    $ref: spending-expectation.yml#/~1spending-expectation~1{id}
  /spending-expectations:
    $ref: spending-expectation.yml#/~1spending-expectations
    
  /prefix:
    $ref: prefix.yml#/~1prefix
  /prefix/{id}:
    $ref: prefix.yml#/~1prefix~1{id}
  /prefixes:
    $ref: prefix.yml#/~1prefixes

#  /address:
#    $ref: address.yml#/~1address
#  /address/{id}:
#    $ref: address.yml#/~1address~1{id}
#  /addresses:
#    $ref: address.yml#/~1addresses
#
#  /address/country:
#    $ref: address.yml#/~1address~1country
#  /address/country/{id}:
#    $ref: address.yml#/~1address~1country~1{id}