schema:
  User:
    type: object
    title: User
    properties:
      id:
        format: int64
        type: integer
      email:
        example: pf@imunixx.de
        type: string
      activated:
        example: false
        type: boolean

  UserCreate:
    type: object
    title: UserCreate
    properties:
      id:
        format: int64
        type: integer
      email:
        example: pf@imunixx.de
        type: string
      password:
        example: 03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4
        type: string
      userCode:
        example: 0
        type: string
      activated:
        example: false
        type: boolean

  UserUpdate:
    type: object
    title: UserUpdate
    properties:
      id:
        format: int64
        type: integer
      email:
        example: pf@imunixx.de
        type: string
      password:
        example: 03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4
        type: string
      userCode:
        example: 0
        type: string
      activated:
        example: false
        type: boolean
